# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c

before_script:
  - export LANG=en_US.UTF-8
  - cd Demo ; pod install ; cd ..

xcode_workspace: Demo/Demo.xcworkspace

xcode_scheme: Demo

xcode_sdk: iphonesimulator
